-- Products are retained for master-data and scan history; deletion is not
-- exposed. normalized_dimensions is generated by the Phase 2 schema.

create or replace function public.create_product(
  p_product_code text,
  p_part_name text,
  p_outer_diameter numeric,
  p_inner_diameter numeric,
  p_length numeric
)
returns table (
  id uuid,
  product_code text,
  part_name text,
  outer_diameter numeric,
  inner_diameter numeric,
  length numeric,
  normalized_dimensions text,
  is_active boolean,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  normalized_code text := lower(btrim(p_product_code));
  normalized_name text := btrim(p_part_name);
begin
  if not private.is_active_admin() then
    raise exception using errcode = 'P0001', message = 'PRODUCT_ADMIN_REQUIRED';
  end if;

  if normalized_code !~ '^[a-z0-9][a-z0-9_-]{1,63}$'
    or normalized_name = ''
    or char_length(normalized_name) > 200
    or p_outer_diameter is null or p_outer_diameter <= 0 or p_outer_diameter > 1000000
    or p_inner_diameter is null or p_inner_diameter <= 0 or p_inner_diameter > 1000000
    or p_length is null or p_length <= 0 or p_length > 1000000 then
    raise exception using errcode = 'P0001', message = 'PRODUCT_INPUT_INVALID';
  end if;

  begin
    insert into public.products (
      product_code, part_name, outer_diameter, inner_diameter, length
    ) values (
      normalized_code, normalized_name, p_outer_diameter, p_inner_diameter, p_length
    ) returning * into id, product_code, part_name, outer_diameter, inner_diameter,
      length, normalized_dimensions, is_active, created_at, updated_at;
  exception when unique_violation then
    raise exception using errcode = 'P0001', message = 'PRODUCT_CODE_EXISTS';
  end;

  insert into public.audit_logs (actor_id, action, entity_type, entity_id, metadata)
  values (
    auth.uid(), 'product.created', 'product', id::text,
    jsonb_build_object(
      'product_code', product_code,
      'normalized_dimensions', normalized_dimensions
    )
  );

  return next;
end;
$$;

create or replace function public.update_product(
  p_product_id uuid,
  p_product_code text,
  p_part_name text,
  p_outer_diameter numeric,
  p_inner_diameter numeric,
  p_length numeric
)
returns table (
  id uuid,
  product_code text,
  part_name text,
  outer_diameter numeric,
  inner_diameter numeric,
  length numeric,
  normalized_dimensions text,
  is_active boolean,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  normalized_code text := lower(btrim(p_product_code));
  normalized_name text := btrim(p_part_name);
begin
  if not private.is_active_admin() then
    raise exception using errcode = 'P0001', message = 'PRODUCT_ADMIN_REQUIRED';
  end if;

  if normalized_code !~ '^[a-z0-9][a-z0-9_-]{1,63}$'
    or normalized_name = ''
    or char_length(normalized_name) > 200
    or p_outer_diameter is null or p_outer_diameter <= 0 or p_outer_diameter > 1000000
    or p_inner_diameter is null or p_inner_diameter <= 0 or p_inner_diameter > 1000000
    or p_length is null or p_length <= 0 or p_length > 1000000 then
    raise exception using errcode = 'P0001', message = 'PRODUCT_INPUT_INVALID';
  end if;

  if exists (
    select 1 from public.packing_session_scans
    where product_id = p_product_id and result = 'accepted'
  ) then
    raise exception using errcode = 'P0001', message = 'PRODUCT_IN_USE';
  end if;

  begin
    update public.products
    set product_code = normalized_code,
        part_name = normalized_name,
        outer_diameter = p_outer_diameter,
        inner_diameter = p_inner_diameter,
        length = p_length
    where public.products.id = p_product_id
    returning * into id, product_code, part_name, outer_diameter, inner_diameter,
      length, normalized_dimensions, is_active, created_at, updated_at;
  exception when unique_violation then
    raise exception using errcode = 'P0001', message = 'PRODUCT_CODE_EXISTS';
  end;

  if not found then
    raise exception using errcode = 'P0001', message = 'PRODUCT_NOT_FOUND';
  end if;

  insert into public.audit_logs (actor_id, action, entity_type, entity_id, metadata)
  values (
    auth.uid(), 'product.updated', 'product', id::text,
    jsonb_build_object(
      'product_code', product_code,
      'normalized_dimensions', normalized_dimensions
    )
  );

  return next;
end;
$$;

create or replace function public.set_product_active(
  p_product_id uuid,
  p_is_active boolean
)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  target_code text;
begin
  if not private.is_active_admin() then
    raise exception using errcode = 'P0001', message = 'PRODUCT_ADMIN_REQUIRED';
  end if;

  update public.products
  set is_active = p_is_active
  where public.products.id = p_product_id
  returning product_code into target_code;

  if not found then
    raise exception using errcode = 'P0001', message = 'PRODUCT_NOT_FOUND';
  end if;

  insert into public.audit_logs (actor_id, action, entity_type, entity_id, metadata)
  values (
    auth.uid(),
    case when p_is_active then 'product.activated' else 'product.deactivated' end,
    'product', p_product_id::text,
    jsonb_build_object('product_code', target_code)
  );
end;
$$;

revoke execute on function public.create_product(text, text, numeric, numeric, numeric) from public, anon;
revoke execute on function public.update_product(uuid, text, text, numeric, numeric, numeric) from public, anon;
revoke execute on function public.set_product_active(uuid, boolean) from public, anon;

grant execute on function public.create_product(text, text, numeric, numeric, numeric) to authenticated;
grant execute on function public.update_product(uuid, text, text, numeric, numeric, numeric) to authenticated;
grant execute on function public.set_product_active(uuid, boolean) to authenticated;
